version: "3.7"
networks:
  default:
    driver: bridge
volumes:
  postgres:
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: crystalshards
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis
      POSTGRES_URL: postgres://postgres@postgres/crystalshards
    ports:
      - "3000:3000"
    command:
      - ./dev/sentry
      - -b
      - shards build server
      - -r
      - ./bin/server
    volumes:
      - ./src:/app/src:cached
      - ./spec:/app/spec:cached
      - ./shard.yml:/app/.sentry.yml:cached
      - ./shard.yml:/app/shard.yml:cached
      - ./shard.lock:/app/shard.lock:cached
      - ./migrate:/app/migrate:cached
  job_runner:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis
      POSTGRES_URL: postgres://postgres@postgres/crystalshards
    volumes:
      - ./src:/app/src:cached
      - ./shard.yml:/app/.sentry.yml:cached
      - ./shard.yml:/app/shard.yml:cached
      - ./shard.lock:/app/shard.lock:cached
    command:
      - ./dev/sentry
      - -b
      - shards build job_runner
      - -r
      - ./bin/job_runner



