version: "3.7"
networks:
  default:
    driver: bridge
volumes:
  cockroachdb:
services:
  cockroachdb:
   image: cockroachdb/cockroach:v19.2.2
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - cockroachdb
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      PORT: 3000
      REDIS_URL: redis://redis
      DATABASE_URL: postgres://postgres:postgres@postgres:26257/crystalshards
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    command:
      - ./dev/sentry
      - -b
      - shards build server
      - -r
      - ./bin/server
    volumes:
      - ./src:/app/src:cached
      - ./spec:/app/spec:cached
      - ./shard.yml:/app/.sentry.yml:cached
      - ./shard.yml:/app/shard.yml:cached
      - ./shard.lock:/app/shard.lock:cached
      - ./migrate:/app/migrate:cached
  job_runner:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      PORT: 3000
      REDIS_URL: redis://redis
      DATABASE_URL: postgres://postgres:postgres@postgres/crystalshards
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./src:/app/src:cached
      - ./shard.yml:/app/.sentry.yml:cached
      - ./shard.yml:/app/shard.yml:cached
      - ./shard.lock:/app/shard.lock:cached
    command:
      - ./dev/sentry
      - -b
      - shards build job_runner
      - -r
      - ./bin/job_runner



