replicaCount: 2
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
workers:
  job-runner:
    replicaCount: 3
    command:
      - ./bin/job_runner
    terminationGracePeriodSeconds: 60
readinessProbe:
  path: "/healthz"
livenessProbe:
  path: "/healthz"
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: 0
